# Generated by Django 4.0.5 on 2022-09-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('code0', models.CharField(blank=True, max_length=100)),
                ('code1', models.CharField(blank=True, max_length=100)),
                ('code2', models.CharField(blank=True, max_length=100)),
                ('code3', models.CharField(blank=True, max_length=100)),
                ('code4', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
