# Generated by Django 4.0.5 on 2022-08-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_alter_contactgoogle1_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactgoogle1',
            name='photo',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
