# Generated by Django 4.0.5 on 2022-09-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_student'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['code0'], name='person_stud_code0_15c01f_idx'),
        ),
    ]
