# Generated by Django 4.0.5 on 2022-08-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_alter_contactgoogle1_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactgoogle1',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactgoogle1',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactgoogle1',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='contactgoogle1',
            name='photo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
